// frontends/vue/src/pages/VehiclesPage.vue
<script setup>
import { ref } from 'vue'

import VehicleForm from '../components/VehicleForm.vue'
import VehicleTable from '../components/VehicleTable.vue'
import { useVehicles } from '../composables/useVehicles'

const {
  vehicles,
  filter,
  filteredVehicles,
  isLoading,
  errorMessage,
  createVehicle,
  updateVehicle,
  deleteVehicle,
} = useVehicles()

const editingVehicle = ref(null)

function saveVehicle(vehicle) {
  if (editingVehicle.value) {
    updateVehicle(editingVehicle.value.id, vehicle)
    editingVehicle.value = null
    return
  }

  createVehicle(vehicle)
}

function startEditing(vehicle) {
  editingVehicle.value = vehicle
}
</script>

<template>
  <main class="vehicles-page">
    <section class="page-header">
      <div>
        <p class="eyebrow">Logistics fleet</p>
        <h1>Vehicles</h1>
      </div>

      <div class="summary-pill">{{ filteredVehicles.length }} shown / {{ vehicles.length }} total</div>
    </section>

    <p v-if="errorMessage" class="error-message">{{ errorMessage }}</p>

    <section class="content-grid">
      <VehicleForm
        :vehicle-to-edit="editingVehicle"
        @save-vehicle="saveVehicle"
        @clear-edit="editingVehicle = null"
      />

      <section class="table-area">
        <div class="filters">
          <button type="button" :class="{ active: filter === 'all' }" @click="filter = 'all'">
            All
          </button>
          <button
            type="button"
            :class="{ active: filter === 'available' }"
            @click="filter = 'available'"
          >
            Available
          </button>
          <button
            type="button"
            :class="{ active: filter === 'unavailable' }"
            @click="filter = 'unavailable'"
          >
            Unavailable
          </button>
        </div>

        <p v-if="isLoading" class="loading-message">Loading vehicles...</p>
        <VehicleTable
          v-else
          :vehicles="filteredVehicles"
          @edit-vehicle="startEditing"
          @delete-vehicle="deleteVehicle"
        />
      </section>
    </section>
  </main>
</template>

// frontends/react/frontendReact/src/pages/VehiclesPage.jsx
import VehicleTable  from "../components/VehicleTable";
import VehicleForm from "../components/VehicleForm";
import { useVehicleContext } from '../context/VehicleContext'
import { useCallback, useMemo, useState } from "react";
import VehicleFilters from '../components/VehicleFilters'

function VehiclesPage() {
    const {vehicles, loading, error, createVehicle, updateVehicle, deleteVehicle} = useVehicleContext()
    const [editingVehicle, setEditingVehicle] = useState(null)
    const [filter, setFilter] = useState('all')

    const handleFilterChange = useCallback((nextFilter) => {
        setFilter(nextFilter)
    }, [])

    const filteredVehicles = useMemo(() => {
        if (filter === 'all') {
            return vehicles
        }

        const availability = filter === 'available'

        return vehicles.filter((vehicle) => vehicle.available === availability)
    }, [vehicles, filter])

    function handleSubmitVehicle(vehicle) {
        if (editingVehicle) {
            updateVehicle(editingVehicle.id, vehicle)
            setEditingVehicle(null)
            return
    }

  createVehicle(vehicle)
    }

    if (loading) {
        return <p>Loading vehicles...</p>
    }

    return (
        <main className="app-page">
            <section className="page-header">
                <h1>Vehicles</h1>
                <p>Manage logistics fleet records</p>
            </section>

            {error && <p className="error-message">{error}</p>}

            <VehicleForm
            vehicleToEdit={editingVehicle}
        onCreateVehicle={handleSubmitVehicle}
        />

        <VehicleFilters filter={filter} onFilterChange={handleFilterChange} />

        <VehicleTable
        vehicles={filteredVehicles}
        onDeleteVehicle={deleteVehicle}
        onEditVehicle={setEditingVehicle}
        />
    </main>
    )
}

export default VehiclesPage

//component composition
