// frontends/react/frontendReact/src/components/VehicleTable.jsx
import { Link } from 'react-router-dom'

function VehicleTable({ vehicles, onDeleteVehicle, onEditVehicle }) {
  return (
    <div className="table-shell">
      <table className="vehicle-table">
        <thead>
          <tr>
            <th>Registration</th>
            <th>Type</th>
            <th>Capacity</th>
            <th>Availability</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          {vehicles.length === 0 ? (
            <tr>
              <td colSpan="5" className="empty-table-cell">
                No vehicles found.
              </td>
            </tr>
          ) : (
            vehicles.map((vehicle) => (
              <tr key={vehicle.id}>
                <td>
                  <Link className="table-link" to={`/vehicles/${vehicle.id}`}>
                    {vehicle.registrationNumber}
                  </Link>
                </td>
                <td>{vehicle.type}</td>
                <td>{vehicle.capacityKg} kg</td>
                <td>
                  <span
                    className={
                      vehicle.available
                        ? 'status available'
                        : 'status unavailable'
                    }
                  >
                    {vehicle.available ? 'Available' : 'Unavailable'}
                  </span>
                </td>
                <td className="table-actions">
                  <button type="button" onClick={() => onEditVehicle(vehicle)}>
                    Edit
                  </button>
                  <button
                    type="button"
                    onClick={() => onDeleteVehicle(vehicle.id)}
                  >
                    Delete
                  </button>
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>
    </div>
  )
}

export default VehicleTable

// frontends/vue/src/components/VehicleTable.vue
<script setup>
defineProps({
  vehicles: {
    type: Array,
    required: true,
  },
})

defineEmits(['edit-vehicle', 'delete-vehicle'])
</script>

<template>
  <div class="table-shell">
    <table>
      <thead>
        <tr>
          <th>Registration</th>
          <th>Type</th>
          <th>Capacity</th>
          <th>Available</th>
          <th class="actions-column">Actions</th>
        </tr>
      </thead>

      <tbody>
        <tr v-if="vehicles.length === 0">
          <td class="empty-cell" colspan="5">No vehicles found.</td>
        </tr>

        <tr v-for="vehicle in vehicles" :key="vehicle.id">
          <td>
            <RouterLink class="table-link" :to="`/vehicles/${vehicle.id}`">
              {{ vehicle.registrationNumber }}
            </RouterLink>
          </td>
          <td>{{ vehicle.type }}</td>
          <td>{{ vehicle.capacityKg }} kg</td>
          <td>
            <span class="status-pill" :class="{ unavailable: !vehicle.available }">
              {{ vehicle.available ? 'Yes' : 'No' }}
            </span>
          </td>
          <td class="actions-cell">
            <button type="button" @click="$emit('edit-vehicle', vehicle)">Edit</button>
            <button type="button" class="danger-button" @click="$emit('delete-vehicle', vehicle.id)">
              Delete
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
